{% set version = "0.0.19" %}
{% set blake2_sha256 = "348ec5d2f9da2d0f62c8ecc824d32d253f4e8fdf4675fa9acb3ae267a117f60e" %}

package:
  name: clinker-py
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/{{ blake2_sha256[0:2] }}/{{ blake2_sha256[2:4] }}/{{ blake2_sha256[4:] }}/clinker-{{ version }}.tar.gz
  sha256: 34884f885736ceeed8b876ea656b00e2a144438766e58ea8483d3c66cbfae5de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - biopython >=1.75
    - numpy >=1.13.3
    - scipy >=1.3.3
    - gffutils
    
test:
  commands:
    - clinker -h

about:
  home: "https://github.com/gamcil/clinker"
  license: MIT
  license_family: MIT
  summary: "Gene cluster comparison figure generator"

extra:
  identifiers:
    - doi:10.5281/zenodo.4326585
